<?php
/**
 * Device Import API
 * Handles Excel bulk upload and device registry management
 */

header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, PUT, DELETE');
header('Access-Control-Allow-Headers: Content-Type');

require_once __DIR__ . '/../config.php';
require_once __DIR__ . '/../db.php';
require_once __DIR__ . '/../auth.php';
require_once __DIR__ . '/../core/email_template.php';

// Initialize authentication
$auth = new Auth($conn);

// Get authenticated user
function getAuthenticatedUser($auth) {
    if ($auth->isLoggedIn()) {
        $user = $auth->getUser();
        return $user['username'] ?? 'system';
    }
    return 'system';
}

// Database connection (reuse existing connection from db.php)
function getDBConnection() {
    global $conn;
    return $conn;
}

// Normalize MAC address
function normalizeMac($mac) {
    $mac = strtoupper(preg_replace('/[^0-9A-Fa-f]/', '', $mac));
    if (strlen($mac) === 12) {
        return implode(':', str_split($mac, 2));
    }
    return null;
}

// Validate IP address
function validateIP($ip) {
    return filter_var($ip, FILTER_VALIDATE_IP) !== false;
}

/**
 * Return true when $mac is a locally-administered (randomised / virtual) address.
 *
 * The IEEE 802 standard reserves bit 1 of the first octet to indicate whether a
 * MAC was globally assigned (OUI-based) or locally administered (e.g. randomly
 * generated by a WiFi client or a virtual-machine hypervisor).  Such addresses
 * must never be treated as unregistered physical devices.
 *
 * @param  string $mac  Colon-separated or plain-hex MAC in any case (e.g. "7A:B3:…")
 * @return bool
 */
function isLocallyAdministeredMac(string $mac): bool {
    $firstOctet = hexdec(substr(str_replace(':', '', $mac), 0, 2));
    return (bool)($firstOctet & 0x02);
}

/**
 * Return true when the error message indicates a SQL Server or MySQL deadlock.
 * SQL Server deadlocks have SQLSTATE 40001 (error 1205) in the error string.
 * MySQL deadlocks have error code 1213 in the error string.
 */
function isDeadlockError(?string $errorMsg): bool {
    if (!$errorMsg) return false;
    return strpos($errorMsg, '40001') !== false
        || strpos($errorMsg, '1205')  !== false
        || strpos($errorMsg, '1213')  !== false
        || stripos($errorMsg, 'deadlock') !== false;
}

/**
 * Execute a prepared statement with automatic deadlock retry.
 * On SQL Server (SQLSTATE 40001) or MySQL (1213) deadlocks, the statement
 * is re-executed up to $maxRetries times with exponential back-off.
 *
 * @param  object $stmt        Prepared MysqliPdoStmt (already bound)
 * @param  int    $maxRetries  Maximum additional attempts after the first failure
 * @return bool                True on success
 */
function executeWithDeadlockRetry(object $stmt, int $maxRetries = 5): bool {
    for ($attempt = 0; $attempt <= $maxRetries; $attempt++) {
        $ok = $stmt->execute();
        if ($ok) return true;
        if ($attempt < $maxRetries && isDeadlockError($stmt->error ?? '')) {
            // SQL Server deadlock detection runs every ~5 s, so the back-off
            // must be long enough to let the lock cycle clear.
            // Exponential back-off starting at 1 s: 1 s, 2 s, 4 s, 8 s, 16 s.
            usleep(1000000 * (1 << $attempt));
            continue;
        }
        break;
    }
    // Log only after all retries are exhausted.
    if ($stmt->error) {
        error_log("executeWithDeadlockRetry failed after {$maxRetries} retries: " . $stmt->error);
    }
    return false;
}

/**
 * Read SMTP config from snmp_worker/config/config.yml and return parsed email settings.
 * Returns null if email is disabled or config unreadable.
 */
function getSmtpConfig() {
    $configPath = __DIR__ . '/../snmp_worker/config/config.yml';
    if (!file_exists($configPath)) return null;
    $content = @file_get_contents($configPath);
    if (!$content) return null;

    // Extract the email: block using regex (same approach as snmp_admin.php)
    if (!preg_match(
        '/email:\s+enabled:\s*(true|false)\s+smtp_host:\s*"([^"]*)"\s+smtp_port:\s*([^\s]+)\s+smtp_user:\s*"([^"]*)"\s+smtp_password:\s*"([^"]*)"\s+from_address:\s*"([^"]*)"/s',
        $content, $m
    )) return null;

    if ($m[1] !== 'true') return null; // email disabled

    // Parse to_addresses list
    $toAddresses = [];
    if (preg_match('/to_addresses:\s*((?:\s*-\s*"[^"]*"\s*)+)/', $content, $tm)) {
        preg_match_all('/-\s*"([^"]*)"/', $tm[1], $addrMatches);
        $toAddresses = array_filter($addrMatches[1]);
    }

    if (empty($toAddresses)) return null;

    return [
        'smtp_host'     => $m[2],
        'smtp_port'     => (int)$m[3],
        'smtp_user'     => $m[4],
        'smtp_password' => $m[5],
        'from_address'  => $m[6],
        'to_addresses'  => array_values($toAddresses),
    ];
}

/**
 * Get the list of recipient email addresses for a given mail type.
 * Queries alarm_user_email_config for per-user settings; falls back to global to_addresses.
 *
 * @param string $mailType  e.g. 'excel_export', 'mac_history_cleanup'
 * @return array  Email address strings, or empty array if none configured
 */
function getMailTypeRecipients(string $mailType): array {
    global $conn;
    try {
        // Table may not exist yet — create it if missing
        $conn->query(
            "IF OBJECT_ID('dbo.alarm_user_email_config','U') IS NULL BEGIN " .
            "CREATE TABLE alarm_user_email_config (" .
            "alarm_type VARCHAR(100) NOT NULL, user_id INT NOT NULL, email_enabled BIT NOT NULL DEFAULT 1, " .
            "CONSTRAINT PK_alarm_user_email_config PRIMARY KEY (alarm_type, user_id)" .
            ") END"
        );
        // Check whether any per-type rows exist for this mail type
        $chk = $conn->prepare(
            "SELECT COUNT(*) AS cnt FROM alarm_user_email_config WHERE alarm_type = ?"
        );
        $chk->bind_param('s', $mailType);
        $chk->execute();
        $row = $chk->get_result()->fetch_assoc();
        $chk->close();
        if ((int)($row['cnt'] ?? 0) === 0) {
            // No per-type config — fall back to global SMTP to_addresses
            $cfg = getSmtpConfig();
            return $cfg ? $cfg['to_addresses'] : [];
        }
        // Return emails of users opted-in for this mail type
        $stmt = $conn->prepare(
            "SELECT u.email FROM alarm_user_email_config auc " .
            "JOIN users u ON u.id = auc.user_id " .
            "WHERE auc.alarm_type = ? AND auc.email_enabled = 1 " .
            "AND u.is_active = 1 AND u.email IS NOT NULL AND LEN(LTRIM(u.email)) > 0"
        );
        $stmt->bind_param('s', $mailType);
        $stmt->execute();
        $result = $stmt->get_result();
        $emails = [];
        while ($r = $result->fetch_assoc()) {
            $emails[] = $r['email'];
        }
        $stmt->close();
        return $emails;
    } catch (\Throwable $e) {
        // On any error fall back to global list
        $cfg = getSmtpConfig();
        return $cfg ? $cfg['to_addresses'] : [];
    }
}

/**
 * Send an alarm email via SMTP (sync, blocking).
 * Uses fsockopen for port 465 (SSL) or stream_socket_client + STARTTLS for port 587.
 *
 * @param string $subject
 * @param string $htmlBody
 * @param array|null $recipients  Optional override recipient list; defaults to global to_addresses
 * @return bool
 */
function sendAlarmEmail(string $subject, string $htmlBody, array $recipients = null): bool {
    $cfg = getSmtpConfig();
    if (!$cfg) return false;
    if ($recipients !== null) {
        $cfg['to_addresses'] = $recipients;
    }
    if (empty($cfg['to_addresses'])) return false;

    $boundary = md5(uniqid());
    $plainBody = strip_tags(str_replace(['<br>', '<br/>', '<br />'], "\n", $htmlBody));

    $message = "MIME-Version: 1.0\r\n"
        . "Content-Type: multipart/alternative; boundary=\"{$boundary}\"\r\n"
        . "\r\n"
        . "--{$boundary}\r\n"
        . "Content-Type: text/plain; charset=UTF-8\r\n\r\n"
        . $plainBody . "\r\n"
        . "--{$boundary}\r\n"
        . "Content-Type: text/html; charset=UTF-8\r\n\r\n"
        . $htmlBody . "\r\n"
        . "--{$boundary}--\r\n";

    $port = $cfg['smtp_port'];
    $host = $cfg['smtp_host'];
    $user = $cfg['smtp_user'];
    $pass = $cfg['smtp_password'];
    $from = $cfg['from_address'] ?: $user;
    $tos  = $cfg['to_addresses'];

    try {
        $useImplicitTLS = ($port === 465);
        $proto  = $useImplicitTLS ? 'ssl' : 'tcp';
        $ctx    = stream_context_create(['ssl' => ['verify_peer' => false, 'verify_peer_name' => false]]);
        $sock   = @stream_socket_client("{$proto}://{$host}:{$port}", $errno, $errstr, 15,
                                        STREAM_CLIENT_CONNECT, $ctx);
        if (!$sock) return false;
        stream_set_timeout($sock, 15);

        // Read ALL lines of a multi-line SMTP response (e.g. EHLO returns 250-... lines)
        $read = function() use ($sock) {
            $buf = '';
            while (($line = fgets($sock, 1024)) !== false) {
                $buf .= $line;
                if (isset($line[3]) && $line[3] === ' ') break; // last line has space as 4th char
            }
            return trim($buf);
        };

        $greeting = $read();
        if (substr($greeting, 0, 3) !== '220') { fclose($sock); return false; }

        fwrite($sock, "EHLO " . gethostname() . "\r\n");
        $read(); // consume full multi-line EHLO response

        // STARTTLS upgrade for port 587
        if (!$useImplicitTLS) {
            fwrite($sock, "STARTTLS\r\n");
            $r = $read();
            if (substr($r, 0, 3) !== '220') { fclose($sock); return false; }
            if (!stream_socket_enable_crypto($sock, true, STREAM_CRYPTO_METHOD_TLS_CLIENT)) {
                fclose($sock); return false;
            }
            fwrite($sock, "EHLO " . gethostname() . "\r\n");
            $read(); // consume post-STARTTLS EHLO
        }

        // AUTH LOGIN
        fwrite($sock, "AUTH LOGIN\r\n");
        $r = $read();
        if (substr($r, 0, 3) !== '334') { fclose($sock); return false; }
        fwrite($sock, base64_encode($user) . "\r\n");
        $read();
        fwrite($sock, base64_encode($pass) . "\r\n");
        $r = $read();
        if (substr($r, 0, 3) !== '235') { fclose($sock); return false; }

        // Envelope
        fwrite($sock, "MAIL FROM:<{$from}>\r\n"); $read();
        foreach ($tos as $to) {
            fwrite($sock, "RCPT TO:<{$to}>\r\n"); $read();
        }

        // Body
        fwrite($sock, "DATA\r\n"); $read();
        $headers = "From: {$from}\r\nTo: " . implode(', ', $tos) . "\r\nSubject: {$subject}\r\nDate: " . date('r') . "\r\n";
        fwrite($sock, $headers . $message . "\r\n.\r\n");
        $r = $read();
        fwrite($sock, "QUIT\r\n");
        fclose($sock);
        return substr($r, 0, 3) === '250';
    } catch (\Throwable $e) {
        error_log("sendAlarmEmail error: " . $e->getMessage());
        return false;
    }
}

/**
 * Log an email send to the email_log table (best-effort, ignores errors).
 */
function logEmailSent(string $subject, array $recipients, string $mailType, bool $success, string $alarmType = null): void {
    global $conn;
    try {
        $tableCheck = $conn->query("SELECT COUNT(*) as cnt FROM information_schema.tables WHERE table_name='email_log'");
        if (!$tableCheck || !(($r = $tableCheck->fetch_assoc()) && (int)$r['cnt'])) return;
        $recipientsStr = implode(', ', $recipients);
        $status = $success ? 'sent' : 'failed';
        $stmt = $conn->prepare(
            "INSERT INTO email_log (sent_at, subject, recipients, alarm_type, mail_type, status) VALUES (NOW(), ?, ?, ?, ?, ?)"
        );
        $stmt->bind_param('sssss', $subject, $recipientsStr, $alarmType, $mailType, $status);
        $stmt->execute();
        $stmt->close();
    } catch (\Throwable $e) {
        // Silently ignore
    }
}

// ── Lightweight native xlsx / csv reader (no vendor dependency) ──────────────

/**
 * Converts a column letter string (A, B, AA, ...) to a zero-based index.
 */
function _colLetterToIndex(string $col): int {
    $idx = 0;
    $len = strlen($col);
    for ($i = 0; $i < $len; $i++) {
        $idx = $idx * 26 + (ord($col[$i]) - 64);
    }
    return $idx - 1;
}

/**
 * Parse an xlsx file and return its first sheet as a 2-D array.
 * Requires ZipArchive and SimpleXML (both bundled with PHP).
 */
function parseXlsx(string $filePath): array {
    $zip = new ZipArchive();
    if ($zip->open($filePath) !== true) {
        throw new \RuntimeException('xlsx dosyası açılamadı.');
    }

    // Shared strings table
    $sharedStrings = [];
    $ssRaw = $zip->getFromName('xl/sharedStrings.xml');
    if ($ssRaw !== false) {
        $ss = simplexml_load_string($ssRaw);
        foreach ($ss->si as $si) {
            if (isset($si->t)) {
                $sharedStrings[] = (string) $si->t;
            } else {
                $text = '';
                foreach ($si->r as $r) {
                    $text .= (string) $r->t;
                }
                $sharedStrings[] = $text;
            }
        }
    }

    // First worksheet
    $sheetRaw = $zip->getFromName('xl/worksheets/sheet1.xml');
    $zip->close();

    if ($sheetRaw === false) {
        throw new \RuntimeException('Çalışma sayfası okunamadı.');
    }

    $sheet = simplexml_load_string($sheetRaw);
    $rows  = [];

    foreach ($sheet->sheetData->row as $row) {
        $rowData  = [];
        $lastCol  = -1;

        foreach ($row->c as $cell) {
            if (!preg_match('/([A-Z]+)/', (string) $cell['r'], $m)) {
                continue;
            }
            $col = _colLetterToIndex($m[1]);

            // Fill any skipped (empty) columns
            for ($i = $lastCol + 1; $i < $col; $i++) {
                $rowData[] = null;
            }
            $lastCol = $col;

            $type  = (string) ($cell['t'] ?? '');
            $value = (string) ($cell->v ?? '');

            if ($type === 's') {
                $rowData[] = $sharedStrings[(int) $value] ?? '';
            } elseif ($type === 'inlineStr') {
                $rowData[] = (string) ($cell->is->t ?? '');
            } elseif ($type === 'b') {
                $rowData[] = $value === '1';
            } else {
                $rowData[] = $value === '' ? null : $value;
            }
        }

        $rows[] = $rowData;
    }

    return $rows;
}

/**
 * Read an xlsx or csv file and return rows as a 2-D array (like PhpSpreadsheet toArray()).
 */
function readSpreadsheetFile(string $filePath, string $ext): array {
    if ($ext === 'csv') {
        $rows = [];
        if (($handle = fopen($filePath, 'r')) !== false) {
            // Detect and skip UTF-8 BOM
            $bom = fread($handle, 3);
            if (strlen($bom) < 3 || $bom !== "\xEF\xBB\xBF") {
                rewind($handle);
            }
            while (($row = fgetcsv($handle)) !== false) {
                $rows[] = $row;
            }
            fclose($handle);
        }
        return $rows;
    }

    return parseXlsx($filePath);
}

// ── Lightweight native xlsx writer (no vendor dependency) ────────────────────

/**
 * Convert a zero-based column index to an Excel column letter (0→A, 25→Z, 26→AA …).
 */
function _colIndexToLetter(int $idx): string {
    $letter = '';
    $n = $idx + 1;
    while ($n > 0) {
        $rem    = ($n - 1) % 26;
        $letter = chr(65 + $rem) . $letter;
        $n      = (int)(($n - 1) / 26);
    }
    return $letter;
}

/**
 * Escape a string value for embedding in an XML attribute or element.
 */
function _xmlEsc(string $v): string {
    return htmlspecialchars($v, ENT_XML1 | ENT_QUOTES, 'UTF-8');
}

/**
 * Build a minimal, valid .xlsx binary string from a 2-D array.
 *
 * Row 0 is treated as the header row and rendered bold.
 * All values are written as inline strings (t="inlineStr") so no shared-strings
 * table is needed.  Requires ZipArchive (bundled with PHP).
 *
 * @param array $rows  2-D array [ [col0, col1, …], … ]
 * @return string      Raw binary content of the .xlsx file
 */
function buildXlsx(array $rows): string {
    // ── worksheet XML ─────────────────────────────────────────────────────────
    $sheetRows = '';
    foreach ($rows as $ri => $rowData) {
        $rowNum  = $ri + 1;
        $isHdr   = ($ri === 0);
        $cells   = '';
        foreach ($rowData as $ci => $val) {
            $colLetter = _colIndexToLetter($ci);
            $ref       = $colLetter . $rowNum;
            $safe      = _xmlEsc((string)($val ?? ''));
            // s="1" = bold style (defined in styles.xml); s="0" = normal
            $style     = $isHdr ? ' s="1"' : '';
            $cells    .= "<c r=\"{$ref}\" t=\"inlineStr\"{$style}><is><t>{$safe}</t></is></c>";
        }
        $sheetRows .= "<row r=\"{$rowNum}\">{$cells}</row>";
    }

    $sheetXml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        . '<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
        . '<sheetData>' . $sheetRows . '</sheetData>'
        . '</worksheet>';

    // ── styles.xml (2 xf: 0=normal, 1=bold header) ───────────────────────────
    $stylesXml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        . '<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">'
        . '<fonts count="2">'
        .   '<font><sz val="11"/><name val="Calibri"/></font>'
        .   '<font><b/><sz val="11"/><name val="Calibri"/></font>'
        . '</fonts>'
        . '<fills count="2">'
        .   '<fill><patternFill patternType="none"/></fill>'
        .   '<fill><patternFill patternType="gray125"/></fill>'
        . '</fills>'
        . '<borders count="1">'
        .   '<border><left/><right/><top/><bottom/><diagonal/></border>'
        . '</borders>'
        . '<cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs>'
        . '<cellXfs count="2">'
        .   '<xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/>'
        .   '<xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1"/>'
        . '</cellXfs>'
        . '</styleSheet>';

    // ── workbook & relationship XML ───────────────────────────────────────────
    $workbookXml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        . '<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"'
        . ' xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">'
        . '<sheets><sheet name="Kayıtlar" sheetId="1" r:id="rId1"/></sheets>'
        . '</workbook>';

    $wbRelsXml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        . '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        . '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>'
        . '<Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/>'
        . '</Relationships>';

    $dotRelsXml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        . '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        . '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>'
        . '</Relationships>';

    $contentTypesXml = '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        . '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        . '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        . '<Default Extension="xml" ContentType="application/xml"/>'
        . '<Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>'
        . '<Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>'
        . '<Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>'
        . '</Types>';

    // ── assemble into a ZIP (xlsx = ZIP) ──────────────────────────────────────
    $tmp = tempnam(sys_get_temp_dir(), 'xlsx_');
    $zip = new ZipArchive();
    if ($zip->open($tmp, ZipArchive::OVERWRITE) !== true) {
        throw new \RuntimeException('Geçici xlsx dosyası oluşturulamadı.');
    }
    $zip->addFromString('[Content_Types].xml',          $contentTypesXml);
    $zip->addFromString('_rels/.rels',                  $dotRelsXml);
    $zip->addFromString('xl/workbook.xml',              $workbookXml);
    $zip->addFromString('xl/_rels/workbook.xml.rels',   $wbRelsXml);
    $zip->addFromString('xl/styles.xml',                $stylesXml);
    $zip->addFromString('xl/worksheets/sheet1.xml',     $sheetXml);
    $zip->close();

    $content = file_get_contents($tmp);
    unlink($tmp);
    return $content;
}

// ─────────────────────────────────────────────────────────────────────────────

// Handle Excel file upload
if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_FILES['excel_file'])) {
    $file = $_FILES['excel_file'];
    
    // Validate file
    $allowed_extensions = ['xlsx', 'csv'];
    $file_ext = strtolower(pathinfo($file['name'], PATHINFO_EXTENSION));
    
    if (!in_array($file_ext, $allowed_extensions)) {
        echo json_encode(['error' => 'Geçersiz dosya türü. Lütfen xlsx veya csv dosyası yükleyin.']);
        exit;
    }
    
    try {
        $rows = readSpreadsheetFile($file['tmp_name'], $file_ext);
        
        // Get header row to detect format
        $header = array_shift($rows);
        
        // Detect format based on header row
        // New format: "IP Adresi" or similar in first column
        // Old format: "MAC" or similar in first column
        $is_new_format = false;
        
        if (!empty($header)) {
            $first_header = strtolower(trim($header[0] ?? ''));
            // Check if first column is IP-related (new format) or MAC-related (old format)
            if (strpos($first_header, 'ip') !== false || count($header) <= 3) {
                $is_new_format = true;
            }
        }
        
        $conn = getDBConnection();
        $success_count = 0;
        $error_count = 0;
        $errors = [];
        
        // Start transaction
        $conn->begin_transaction();
        
        try {
            $updStmt = $conn->prepare("
                UPDATE mac_device_registry
                SET ip_address=?, device_name=?, user_name=?, location=?, department=?, notes=?, source='excel', updated_by=?
                WHERE mac_address=?
            ");
            $insStmt = $conn->prepare("
                INSERT INTO mac_device_registry 
                (mac_address, ip_address, device_name, user_name, location, department, notes, source, created_by)
                VALUES (?, ?, ?, ?, ?, ?, ?, 'excel', ?)
            ");
            $stmt = $updStmt; // compatibility alias
            
            foreach ($rows as $index => $row) {
                $row_num = $index + 2; // +2 for header and 0-index
                
                // Parse based on detected format
                if ($is_new_format) {
                    // New simplified format: IP Adresi | Hostname | MAC Adresi
                    $ip = isset($row[0]) ? trim($row[0]) : null;
                    $device_name = isset($row[1]) ? trim($row[1]) : null;
                    $mac = isset($row[2]) ? normalizeMac($row[2]) : null;
                    $user_name = null;
                    $location = null;
                    $department = null;
                    $notes = null;
                } else {
                    // Old format: MAC, IP, Device Name, User, Location, Department, Notes
                    $mac = isset($row[0]) ? normalizeMac($row[0]) : null;
                    $ip = isset($row[1]) ? trim($row[1]) : null;
                    $device_name = isset($row[2]) ? trim($row[2]) : null;
                    $user_name = isset($row[3]) ? trim($row[3]) : null;
                    $location = isset($row[4]) ? trim($row[4]) : null;
                    $department = isset($row[5]) ? trim($row[5]) : null;
                    $notes = isset($row[6]) ? trim($row[6]) : null;
                }
                
                // Validate
                if (!$mac) {
                    $errors[] = "Row $row_num: Invalid MAC address";
                    $error_count++;
                    continue;
                }
                
                if ($ip && !validateIP($ip)) {
                    $errors[] = "Row $row_num: Invalid IP address ($ip)";
                    $error_count++;
                    continue;
                }
                
                if (!$device_name) {
                    $errors[] = "Row $row_num: Hostname is required";
                    $error_count++;
                    continue;
                }
                
                // Insert/Update
                $created_by = getAuthenticatedUser($auth);
                $updStmt->bind_param(
                    'ssssssss',
                    $ip, $device_name, $user_name,
                    $location, $department, $notes, $created_by,
                    $mac
                );
                $updStmt->execute();
                if ($conn->affected_rows == 0) {
                    $insStmt->bind_param(
                        'ssssssss',
                        $mac, $ip, $device_name, $user_name,
                        $location, $department, $notes, $created_by
                    );
                    $insStmt->execute();
                }
                
                if (true) {
                    $success_count++;
                } else {
                    $errors[] = "Row $row_num: Database error - " . $updStmt->error;
                    $error_count++;
                }
            }
            
            $updStmt->close();
            $insStmt->close();
            $stmt_history = $conn->prepare("
                INSERT INTO mac_device_import_history 
                (filename, total_rows, success_count, error_count, errors, imported_by)
                VALUES (?, ?, ?, ?, ?, ?)
            ");
            
            $total_rows = count($rows);
            $errors_json = json_encode($errors);
            $imported_by = getAuthenticatedUser($auth);
            
            $stmt_history->bind_param(
                'siiiss',
                $file['name'], $total_rows, $success_count, $error_count, 
                $errors_json, $imported_by
            );
            $stmt_history->execute();
            $stmt_history->close();
            
            $conn->commit();
            
            echo json_encode([
                'success' => true,
                'message' => "Import completed",
                'total_rows' => $total_rows,
                'success_count' => $success_count,
                'error_count' => $error_count,
                'errors' => $errors
            ]);
            
        } catch (Exception $e) {
            $conn->rollback();
            echo json_encode(['error' => 'Import failed: ' . $e->getMessage()]);
        }
        
        $conn->close();
        
    } catch (Exception $e) {
        echo json_encode(['error' => 'Failed to read file: ' . $e->getMessage()]);
    }
    
    exit;
}

// Handle GET requests
if ($_SERVER['REQUEST_METHOD'] === 'GET') {
    $action = $_GET['action'] ?? '';
    $conn = getDBConnection();
    
    switch ($action) {
        case 'list':
            // List all devices with pagination and search
            $page = isset($_GET['page']) ? max(1, (int)$_GET['page']) : 1;
            $limit = isset($_GET['limit']) ? max(1, min(100, (int)$_GET['limit'])) : 10;
            $offset = ($page - 1) * $limit;
            
            $search = isset($_GET['search']) ? trim($_GET['search']) : '';
            $where_parts = [];
            $params = [];
            $types  = '';
            
            if ($search) {
                $where_parts[] = "(mac_address LIKE ? OR device_name LIKE ? OR ip_address LIKE ?)";
                $search_param = "%$search%";
                $params = [$search_param, $search_param, $search_param];
                $types  = 'sss';
            }

            // Optional MAC-list filter (legacy, kept for backward-compat)
            $mac_filter_raw = isset($_GET['mac_filter']) ? trim($_GET['mac_filter']) : '';
            if ($mac_filter_raw !== '') {
                $mac_list = json_decode($mac_filter_raw, true);
                if (is_array($mac_list) && count($mac_list) > 0) {
                    // Sanitize: keep only valid MAC-looking strings
                    $safe_macs = array_values(array_filter($mac_list, function($m) {
                        return preg_match('/^[0-9A-Fa-f:]{11,17}$/', $m);
                    }));
                    if (count($safe_macs) > 0) {
                        $placeholders = implode(',', array_fill(0, count($safe_macs), '?'));
                        $where_parts[] = "mac_address IN ($placeholders)";
                        $params = array_merge($params, $safe_macs);
                        $types .= str_repeat('s', count($safe_macs));
                    } else {
                        // Filter requested but no valid MACs → return empty result set
                        $where_parts[] = "1=0";
                    }
                } elseif ($mac_filter_raw === '[]') {
                    // Empty array means "none match" → return empty
                    $where_parts[] = "1=0";
                }
            }

            // Status filter: uses match_status column (set by apply_to_ports action)
            $valid_statuses = ['updated', 'already_current', 'unmatched'];
            $status_filter = isset($_GET['status_filter']) ? trim($_GET['status_filter']) : '';
            if ($status_filter !== '' && in_array($status_filter, $valid_statuses, true)) {
                $col_check = $conn->query("SHOW COLUMNS FROM mac_device_registry LIKE 'match_status'");
                if ($col_check && $col_check->num_rows > 0) {
                    $where_parts[] = "match_status = ?";
                    $params[]  = $status_filter;
                    $types    .= 's';
                }
            }

            $where = count($where_parts) ? 'WHERE ' . implode(' AND ', $where_parts) : '';
            
            // Count total
            $count_query = "SELECT COUNT(*) as total FROM mac_device_registry $where";
            $stmt = $conn->prepare($count_query);
            if ($params) {
                $stmt->bind_param($types, ...$params);
            }
            $stmt->execute();
            $row = $stmt->get_result()->fetch_assoc();
            $total = $row ? (int)$row['total'] : 0;
            $stmt->close();
            $totalPages = $total > 0 ? (int)ceil($total / $limit) : 1;
            
            // Get data — use literal integers for LIMIT/OFFSET so db.php's
            // literal-number rewrite is used instead of bound-parameter rewrite,
            // avoiding a pdo_sqlsrv issue where bound OFFSET/FETCH parameters
            // are silently ignored on some driver versions.
            $query = "
                SELECT * FROM mac_device_registry 
                $where
                ORDER BY updated_at DESC
                LIMIT {$limit} OFFSET {$offset}
            ";
            $stmt = $conn->prepare($query);
            if ($params) {
                $stmt->bind_param($types, ...$params);
            }
            $stmt->execute();
            $result = $stmt->get_result();
            
            $devices = [];
            if ($result) {
                while ($row = $result->fetch_assoc()) {
                    $devices[] = $row;
                }
            }
            $stmt->close();
            
            echo json_encode([
                'success' => true,
                'total' => $total,
                'page' => $page,
                'limit' => $limit,
                'totalPages' => $totalPages,
                'devices' => $devices
            ]);
            break;
        
        case 'get':
            // Get single device
            $mac = isset($_GET['mac']) ? normalizeMac($_GET['mac']) : null;
            
            if (!$mac) {
                echo json_encode(['error' => 'MAC address required']);
                break;
            }
            
            $stmt = $conn->prepare("SELECT * FROM mac_device_registry WHERE mac_address = ?");
            $stmt->bind_param('s', $mac);
            $stmt->execute();
            $result = $stmt->get_result();
            
            if ($row = $result->fetch_assoc()) {
                echo json_encode(['success' => true, 'device' => $row]);
            } else {
                echo json_encode(['error' => 'Device not found']);
            }
            $stmt->close();
            break;
        
        case 'get_by_name':
            // Get single device by exact device_name
            $name = isset($_GET['name']) ? trim($_GET['name']) : null;
            
            if (!$name) {
                echo json_encode(['error' => 'Device name required']);
                break;
            }
            
            $stmt = $conn->prepare("SELECT * FROM mac_device_registry WHERE device_name = ? LIMIT 1");
            $stmt->bind_param('s', $name);
            $stmt->execute();
            $result = $stmt->get_result();
            
            if ($row = $result->fetch_assoc()) {
                echo json_encode(['success' => true, 'device' => $row]);
            } else {
                echo json_encode(['success' => false, 'error' => 'Device not found']);
            }
            $stmt->close();
            break;

        case 'history':
            // Get import history
            $limit = isset($_GET['limit']) ? (int)$_GET['limit'] : 10;
            
            $stmt = $conn->prepare("
                SELECT * FROM mac_device_import_history 
                ORDER BY import_date DESC 
                LIMIT ?
            ");
            $stmt->bind_param('i', $limit);
            $stmt->execute();
            $result = $stmt->get_result();
            
            $history = [];
            while ($row = $result->fetch_assoc()) {
                $history[] = $row;
            }
            $stmt->close();
            
            echo json_encode(['success' => true, 'history' => $history]);
            break;

        case 'export_xlsx':
            // Export mac_device_registry as .xlsx download (native PHP, no vendor)
            $rows = [['IP Adresi', 'Hostname', 'MAC Adresi', 'Kaynak', 'Güncelleme']];
            $res = $conn->query(
                "SELECT ip_address, device_name, mac_address, source, updated_at
                 FROM mac_device_registry
                 ORDER BY updated_at DESC"
            );
            if ($res) {
                while ($row = $res->fetch_assoc()) {
                    $rows[] = [
                        $row['ip_address'] ?? '',
                        $row['device_name'] ?? '',
                        $row['mac_address'] ?? '',
                        $row['source'] ?? '',
                        $row['updated_at'] ?? '',
                    ];
                }
            }
            $xlsxContent   = buildXlsx($rows);
            $filename      = 'device_registry_' . date('Ymd_His') . '.xlsx';
            $recordCount   = count($rows) - 1; // exclude header row
            $downloadedBy  = getAuthenticatedUser($auth);

            // ── Email notification: who downloaded, when, how many records ──
            {
                $dlFullName = '';
                $dlClientIp = $_SERVER['HTTP_X_FORWARDED_FOR']
                    ?? $_SERVER['HTTP_X_REAL_IP']
                    ?? $_SERVER['REMOTE_ADDR']
                    ?? '';
                if ($auth->isLoggedIn()) {
                    $dlUser = $auth->getUser();
                    $dlFullName = $dlUser['full_name'] ?? '';
                }
                $subj = "CHAMADA Excel Export Bildirimi";
                $dlContent = "<p style='margin:0 0 14px;font-size:15px;font-weight:700;color:#3498db;'>📥 Kayıtlar İndirildi (Excel)</p>"
                    . "<p style='margin:4px 0;'><strong style='color:#8899bb;'>Tarih / Saat:</strong> " . date('d.m.Y H:i:s') . "</p>"
                    . "<p style='margin:4px 0;'><strong style='color:#8899bb;'>Dosya adı:</strong> " . htmlspecialchars($filename) . "</p>"
                    . "<p style='margin:4px 0;'><strong style='color:#8899bb;'>Kayıt sayısı:</strong> <span style='color:#d4a017;font-weight:700;'>{$recordCount}</span></p>";
                $body = chamada_email_template('Excel Export Bildirimi', $dlContent, $downloadedBy, $dlFullName, $dlClientIp);
                $excelRecipients = getMailTypeRecipients('excel_export');
                $emailSuccess = sendAlarmEmail($subj, $body, $excelRecipients ?: null);
                logEmailSent($subj, $excelRecipients, 'excel_export', $emailSuccess);
            }

            header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
            header('Content-Disposition: attachment; filename="' . $filename . '"');
            header('Cache-Control: no-cache, must-revalidate');
            header('Content-Length: ' . strlen($xlsxContent));
            echo $xlsxContent;
            $conn->close();
            exit;

        case 'export_csv':
            // Export mac_device_registry as CSV download
            header('Content-Type: text/csv; charset=utf-8');
            header('Content-Disposition: attachment; filename="device_registry_' . date('Ymd_His') . '.csv"');
            header('Cache-Control: no-cache, must-revalidate');
            $out = fopen('php://output', 'w');
            // UTF-8 BOM for Excel compatibility
            fputs($out, "\xEF\xBB\xBF");
            fputcsv($out, ['IP Adresi', 'Hostname', 'MAC Adresi', 'Kaynak', 'Güncelleme']);
            $res = $conn->query(
                "SELECT ip_address, device_name, mac_address, source, updated_at
                 FROM mac_device_registry
                 ORDER BY updated_at DESC"
            );
            if ($res) {
                while ($row = $res->fetch_assoc()) {
                    fputcsv($out, [
                        $row['ip_address'] ?? '',
                        $row['device_name'] ?? '',
                        $row['mac_address'] ?? '',
                        $row['source'] ?? '',
                        $row['updated_at'] ?? '',
                    ]);
                }
            }
            fclose($out);
            $conn->close();
            exit;

        default:
            echo json_encode(['error' => 'Invalid action']);
    }
    
    $conn->close();
    exit;
}

// Handle POST - Manual entry and other actions
if ($_SERVER['REQUEST_METHOD'] === 'POST' && !isset($_FILES['excel_file'])) {
    $data = json_decode(file_get_contents('php://input'), true);
    // Check for action in query params first, then in JSON body
    $action = $_GET['action'] ?? ($data['action'] ?? '');

    // Allow list action via POST (used when mac_filter list is too large for a GET URL)
    if ($action === 'list') {
        $conn = getDBConnection();
        $page   = isset($data['page'])   ? max(1, (int)$data['page'])            : 1;
        $limit  = isset($data['limit'])  ? max(1, min(100, (int)$data['limit']))  : 10;
        $offset = ($page - 1) * $limit;
        $search = isset($data['search']) ? trim($data['search'])                  : '';

        $where_parts = [];
        $params = [];
        $types  = '';

        if ($search) {
            $where_parts[] = "(mac_address LIKE ? OR device_name LIKE ? OR ip_address LIKE ?)";
            $search_param  = "%$search%";
            $params        = [$search_param, $search_param, $search_param];
            $types         = 'sss';
        }

        $mac_filter = isset($data['mac_filter']) ? $data['mac_filter'] : null;
        if (is_array($mac_filter)) {
            if (count($mac_filter) === 0) {
                $where_parts[] = "1=0";
            } else {
                $safe_macs = array_values(array_filter($mac_filter, function($m) {
                    return preg_match('/^[0-9A-Fa-f:]{11,17}$/', $m);
                }));
                if (count($safe_macs) > 0) {
                    $placeholders  = implode(',', array_fill(0, count($safe_macs), '?'));
                    $where_parts[] = "mac_address IN ($placeholders)";
                    $params        = array_merge($params, $safe_macs);
                    $types        .= str_repeat('s', count($safe_macs));
                } else {
                    $where_parts[] = "1=0";
                }
            }
        }

        $where = count($where_parts) ? 'WHERE ' . implode(' AND ', $where_parts) : '';

        $count_query = "SELECT COUNT(*) as total FROM mac_device_registry $where";
        $stmt = $conn->prepare($count_query);
        if ($params) { $stmt->bind_param($types, ...$params); }
        $stmt->execute();
        $row = $stmt->get_result()->fetch_assoc();
        $total = $row ? (int)$row['total'] : 0;
        $stmt->close();

        $totalPages = $total > 0 ? ceil($total / $limit) : 1;

        // Use literal integers for LIMIT/OFFSET (safe: both are validated ints)
        // to avoid pdo_sqlsrv bound-parameter issues with OFFSET/FETCH NEXT.
        $query = "SELECT * FROM mac_device_registry $where ORDER BY updated_at DESC LIMIT {$limit} OFFSET {$offset}";
        $stmt  = $conn->prepare($query);
        if ($params) {
            $stmt->bind_param($types, ...$params);
        }
        $stmt->execute();
        $result  = $stmt->get_result();
        $devices = [];
        if ($result) { while ($row = $result->fetch_assoc()) { $devices[] = $row; } }
        $stmt->close();

        echo json_encode([
            'success'    => true,
            'total'      => $total,
            'page'       => $page,
            'limit'      => $limit,
            'totalPages' => $totalPages,
            'devices'    => $devices,
        ]);
        exit;
    }

    if ($action === 'manual_add') {
        $ip = isset($data['ip_address']) ? trim($data['ip_address']) : null;
        $hostname = isset($data['hostname']) ? trim($data['hostname']) : null;
        $mac = isset($data['mac_address']) ? normalizeMac($data['mac_address']) : null;
        
        // Validate inputs
        $errors = [];
        
        if (!$mac) {
            $errors[] = 'Invalid MAC address format';
        }
        
        if (!$ip || !validateIP($ip)) {
            $errors[] = 'Invalid IP address format';
        }
        
        if (!$hostname) {
            $errors[] = 'Hostname is required';
        }
        
        if (count($errors) > 0) {
            echo json_encode(['success' => false, 'errors' => $errors]);
            exit;
        }
        
        $conn = getDBConnection();
        
        try {
            $created_by = getAuthenticatedUser($auth);
            $upd = $conn->prepare("UPDATE mac_device_registry SET ip_address=?, device_name=?, source='manual', updated_by=? WHERE mac_address=?");
            $upd->bind_param('ssss', $ip, $hostname, $created_by, $mac);
            $upd->execute();
            if ($conn->affected_rows == 0) {
                $ins2 = $conn->prepare("INSERT INTO mac_device_registry (mac_address, ip_address, device_name, source, created_by) VALUES (?, ?, ?, 'manual', ?)");
                $ins2->bind_param('ssss', $mac, $ip, $hostname, $created_by);
                $ins2->execute();
                $ins2->close();
            }
            $upd->close();
            $stmt = $upd; // for compatibility with existing execute check
            
            if (true) {
                echo json_encode([
                    'success' => true,
                    'message' => 'Device added successfully',
                    'device' => [
                        'mac_address' => $mac,
                        'ip_address' => $ip,
                        'device_name' => $hostname
                    ]
                ]);
            } else {
                echo json_encode(['success' => false, 'error' => 'Database error: ' . $stmt->error]);
            }
            
            $stmt->close();
        } catch (Exception $e) {
            echo json_encode(['success' => false, 'error' => $e->getMessage()]);
        }
        
        $conn->close();
        exit;
    }
    
    // Update existing device
    if ($action === 'update') {
        $originalMac = isset($data['original_mac']) ? normalizeMac($data['original_mac']) : null;
        $newMac = isset($data['mac_address']) ? normalizeMac($data['mac_address']) : null;
        $ip = isset($data['ip_address']) ? trim($data['ip_address']) : null;
        $hostname = isset($data['device_name']) ? trim($data['device_name']) : null;
        
        // Validate inputs
        $errors = [];
        
        if (!$originalMac) {
            $errors[] = 'Original MAC address is required';
        }
        
        if (!$newMac) {
            $errors[] = 'Invalid new MAC address format';
        }
        
        if ($ip && !validateIP($ip)) {
            $errors[] = 'Invalid IP address format';
        }
        
        if (!$hostname) {
            $errors[] = 'Hostname is required';
        }
        
        if (count($errors) > 0) {
            echo json_encode(['success' => false, 'error' => implode(', ', $errors)]);
            exit;
        }
        
        $conn = getDBConnection();
        
        try {
            $conn->begin_transaction();

            // If MAC changed, delete old record and insert new one
            if ($originalMac !== $newMac) {
                // Delete old record
                $stmt = $conn->prepare("DELETE FROM mac_device_registry WHERE mac_address = ?");
                $stmt->bind_param('s', $originalMac);
                $stmt->execute();
                $stmt->close();
            }
            
            // Insert or update with new data
            $updated_by = getAuthenticatedUser($auth);
            $upd2 = $conn->prepare("UPDATE mac_device_registry SET ip_address=?, device_name=?, source='manual', updated_by=? WHERE mac_address=?");
            $upd2->bind_param('ssss', $ip, $hostname, $updated_by, $newMac);
            $upd2->execute();
            if ($conn->affected_rows == 0) {
                $ins3 = $conn->prepare("INSERT INTO mac_device_registry (mac_address, ip_address, device_name, source, created_by) VALUES (?, ?, ?, 'manual', ?)");
                $ins3->bind_param('ssss', $newMac, $ip, $hostname, $updated_by);
                $ins3->execute();
                $ins3->close();
            }
            $upd2->close();
            $stmt = $upd2; // for compatibility
            
            if (true) {
                $conn->commit();
                echo json_encode([
                    'success' => true,
                    'message' => 'Device updated successfully',
                    'device' => [
                        'mac_address' => $newMac,
                        'ip_address' => $ip,
                        'device_name' => $hostname
                    ]
                ]);
            } else {
                $conn->rollback();
                echo json_encode(['success' => false, 'error' => 'Database error: ' . $stmt->error]);
            }
            
            $stmt->close();
        } catch (Exception $e) {
            $conn->rollback();
            echo json_encode(['success' => false, 'error' => $e->getMessage()]);
        }
        
        $conn->close();
        exit;
    }
    
    // Handle sync_and_scan action — runs apply_to_ports then scan_unregistered in one call.
    // This is the combined "Senkronize Et & Tara" button action and also used by the
    // hourly auto-run on the Device Import page.
    if ($action === 'sync_and_scan') {
        $conn = getDBConnection();

        try {
            // ── Phase 1: apply_to_ports ──────────────────────────────────────
            $apply_updated_count      = 0;
            $apply_updated_macs       = [];
            $apply_already_current    = [];
            $apply_unmatched_macs     = [];

            // Load MACs that were previously matched (ever seen by SNMP) so
            // that temporarily-offline devices are not re-labelled as unmatched.
            // Only MACs that have NEVER been seen by SNMP should get 'unmatched'.
            $prevMatchedSet = [];
            $prevColCheck = $conn->query("SHOW COLUMNS FROM mac_device_registry LIKE 'match_status'");
            if ($prevColCheck && $prevColCheck->num_rows > 0) {
                $prevRes = $conn->query("SELECT mac_address FROM mac_device_registry WHERE match_status IN ('updated', 'already_current')");
                if ($prevRes) {
                    while ($r = $prevRes->fetch_assoc()) {
                        $prevMatchedSet[strtolower(str_replace(':', '', $r['mac_address']))] = true;
                    }
                    $prevRes->close();
                }
            }

            $regResult = $conn->query("
                SELECT mac_address, ip_address, device_name
                FROM mac_device_registry
                WHERE mac_address IS NOT NULL
                  AND device_name IS NOT NULL
                  AND (source IS NULL OR source != 'snmp_hub_auto')
            ");

            if ($regResult) {
                while ($device = $regResult->fetch_assoc()) {
                    $mac          = $device['mac_address'];
                    $ip           = $device['ip_address'] ?? '';
                    $hostname     = $device['device_name'];
                    // Skip only when ip is non-empty AND invalid (e.g. VLAN label string).
                    // Devices imported without an IP are still applied (device name written,
                    // existing port IP preserved via COALESCE in the UPDATE statement).
                    if (!empty($ip) && !validateIP($ip)) { continue; }
                    $macNormalized = strtolower(str_replace(':', '', $mac));

                    $checkStmt = $conn->prepare("
                        SELECT COUNT(*) as cnt FROM ports WITH(NOLOCK)
                        WHERE CHARINDEX(?, LOWER(REPLACE(mac, ':', ''))) > 0
                        AND mac IS NOT NULL AND mac != ''
                    ");
                    $portExists = false;
                    if ($checkStmt) {
                        $checkStmt->bind_param('s', $macNormalized);
                        $checkStmt->execute();
                        $portExists = ($checkStmt->get_result()->fetch_assoc()['cnt'] ?? 0) > 0;
                        $checkStmt->close();
                    }

                    $trackingPortId = null;
                    if (!$portExists) {
                        $macHex = strtoupper(str_replace(':', '', $mac));
                        $tStmt  = $conn->prepare("
                            SELECT p.id
                            FROM mac_address_tracking mat
                            JOIN snmp_devices sd ON sd.id = mat.current_device_id
                            JOIN switches sw ON sw.name = sd.name
                            JOIN ports p ON p.switch_id = sw.id
                                         AND p.port_no = mat.current_port_number
                            WHERE UPPER(REPLACE(mat.mac_address, ':', '')) = ?
                            LIMIT 1
                        ");
                        if ($tStmt) {
                            $tStmt->bind_param('s', $macHex);
                            $tStmt->execute();
                            $tRow = $tStmt->get_result()->fetch_assoc();
                            if ($tRow) { $portExists = true; $trackingPortId = (int)$tRow['id']; }
                            $tStmt->close();
                        }
                    }

                    if (!$portExists) {
                        // If this MAC was seen by SNMP in a previous run, it is
                        // temporarily offline — preserve its matched status rather
                        // than marking it unmatched. Only devices that have NEVER
                        // been matched should receive the 'unmatched' label.
                        if (isset($prevMatchedSet[$macNormalized])) {
                            $apply_already_current[] = $mac;
                        } else {
                            $apply_unmatched_macs[] = $mac;
                        }
                    }

                    if ($trackingPortId !== null) {
                        $updStmt = $conn->prepare("
                            UPDATE ports
                            SET ip = COALESCE(NULLIF(?, ''), ip), device = ?,
                                mac = CASE WHEN (mac IS NULL OR mac = '') THEN ? ELSE CONCAT(mac, ',', ?) END
                            WHERE id = ?
                              AND CHARINDEX(?, LOWER(REPLACE(COALESCE(mac,''), ':', ''))) = 0
                        ");
                        if ($updStmt) {
                            $macColon = $mac;
                            $updStmt->bind_param('ssssis', $ip, $hostname, $macColon, $macColon, $trackingPortId, $macNormalized);
                            executeWithDeadlockRetry($updStmt);
                            if ($updStmt->affected_rows > 0) {
                                $apply_updated_macs[]  = $mac;
                                $apply_updated_count  += $updStmt->affected_rows;
                            } else { $apply_already_current[] = $mac; }
                            $updStmt->close();
                        } else { $apply_already_current[] = $mac; }
                    } else {
                        $updateStmt = $conn->prepare("
                            UPDATE ports WITH (ROWLOCK)
                            SET ip = COALESCE(NULLIF(?, ''), ip), device = ?
                            WHERE CHARINDEX(?, LOWER(REPLACE(mac, ':', ''))) > 0
                            AND mac IS NOT NULL AND mac != ''
                        ");
                        if ($updateStmt) {
                            $updateStmt->bind_param('sss', $ip, $hostname, $macNormalized);
                            executeWithDeadlockRetry($updateStmt);
                            if ($portExists) {
                                if ($updateStmt->affected_rows > 0) {
                                    $apply_updated_macs[] = $mac;
                                    $apply_updated_count += $updateStmt->affected_rows;
                                } else { $apply_already_current[] = $mac; }
                            }
                            $updateStmt->close();
                        }
                    }
                }
                $regResult->close();

                // Persist match_status
                $colCheck = $conn->query("SHOW COLUMNS FROM mac_device_registry LIKE 'match_status'");
                if ($colCheck && $colCheck->num_rows > 0) {
                    $conn->query("UPDATE mac_device_registry SET match_status = NULL WHERE match_status IS NOT NULL");
                    $statusBatch = [
                        'updated'         => array_values(array_unique($apply_updated_macs)),
                        'already_current' => array_values(array_unique($apply_already_current)),
                        'unmatched'       => array_values(array_unique($apply_unmatched_macs)),
                    ];
                    foreach ($statusBatch as $statusVal => $macList) {
                        foreach ($macList as $m) {
                            $stStmt = $conn->prepare("UPDATE mac_device_registry SET match_status = ? WHERE mac_address = ?");
                            if ($stStmt) { $stStmt->bind_param('ss', $statusVal, $m); $stStmt->execute(); $stStmt->close(); }
                        }
                    }
                }
            }

            // ── Phase 2: scan_unregistered ───────────────────────────────────
            $scan_total       = 0;
            $scan_created     = 0;
            $scan_skipped     = 0;
            $scan_ports_upd   = 0;

            $scanResult = $conn->query("
                SELECT mat.mac_address,
                       mat.current_device_id,
                       mat.current_port_number,
                       mat.device_name,
                       mat.ip_address
                FROM mac_address_tracking mat
                LEFT JOIN mac_device_registry mdr
                       ON UPPER(REPLACE(mdr.mac_address, ':', '')) COLLATE utf8mb4_general_ci
                        = UPPER(REPLACE(mat.mac_address, ':', '')) COLLATE utf8mb4_general_ci
                LEFT JOIN port_status_data psd
                       ON psd.device_id    = mat.current_device_id
                      AND psd.port_number  = mat.current_port_number
                WHERE mdr.mac_address IS NULL
                  AND mat.current_device_id IS NOT NULL
                  AND mat.last_seen >= DATE_SUB(NOW(), INTERVAL 24 HOUR)
                  AND (psd.vlan_id IS NULL OR psd.vlan_id NOT IN (70, 30, 40, 50, 130, 140, 254))
                ORDER BY mat.last_seen DESC
            ");

            if ($scanResult) {
                $candidates = [];
                while ($row = $scanResult->fetch_assoc()) {
                    $mac = strtoupper(trim($row['mac_address']));
                    // Skip locally-administered (randomised/WiFi-client) MAC addresses.
                    if (isLocallyAdministeredMac($mac)) {
                        continue;
                    }
                    $candidates[] = [
                        'mac'      => $mac,
                        'deviceId' => intval($row['current_device_id']),
                        'portNo'   => intval($row['current_port_number']),
                        'devName'  => $row['device_name'] ?? '',
                        'ip'       => $row['ip_address'] ?? '',
                    ];
                }
                $scanResult->close();

                $scan_total = count($candidates);

                if ($scan_total > 0) {
                    $macList      = array_column($candidates, 'mac');
                    $placeholders = implode(',', array_fill(0, count($macList), '?'));
                    $types        = str_repeat('s', count($macList));
                    $activeStmt   = $conn->prepare("
                        SELECT new_value FROM alarms
                        WHERE alarm_type = 'mac_added' AND status = 'ACTIVE'
                          AND new_value IN ($placeholders)
                    ");
                    $alreadyActive = [];
                    if ($activeStmt) {
                        $activeStmt->bind_param($types, ...$macList);
                        $activeStmt->execute();
                        $activeRes = $activeStmt->get_result();
                        while ($r = $activeRes->fetch_row()) { $alreadyActive[$r[0]] = true; }
                        $activeStmt->close();
                    }

                    $insStmt = $conn->prepare("
                        INSERT INTO alarms
                            (device_id, port_number, alarm_type, severity, status,
                             title, message, old_value, new_value,
                             first_occurrence, last_occurrence, occurrence_count,
                             created_at, updated_at)
                        VALUES (?, ?, 'mac_added', 'MEDIUM', 'ACTIVE',
                                ?, ?, '', ?,
                                NOW(), NOW(), 1, NOW(), NOW())
                    ");
                    $portIpStmt = $conn->prepare("
                        UPDATE ports SET ip = ?
                        WHERE LOWER(REPLACE(mac, ':', '')) = ?
                          AND mac IS NOT NULL AND mac != ''
                          AND (ip IS NULL OR ip = '')
                    ");

                    foreach ($candidates as $c) {
                        $mac     = $c['mac'];
                        $devId   = $c['deviceId'];
                        $portNo  = $c['portNo'];
                        $devName = $c['devName'];
                        $ip      = $c['ip'];

                        if (!empty($ip) && validateIP($ip) && $portIpStmt) {
                            $macNorm = strtolower(str_replace(':', '', $mac));
                            $portIpStmt->bind_param('ss', $ip, $macNorm);
                            executeWithDeadlockRetry($portIpStmt);
                            if ($portIpStmt->affected_rows > 0) { $scan_ports_upd++; }
                        }

                        if (isset($alreadyActive[$mac])) { $scan_skipped++; continue; }

                        $title   = "Kayıtsız MAC: $mac";
                        $message = "Port $portNo üzerinde Device Import kaydı olmayan MAC tespit edildi: $mac" .
                                   ($ip ? " (IP: $ip)" : '') .
                                   ($devName ? " (Cihaz: $devName)" : '') .
                                   ". Cihazı kaydetmek için Device Import sayfasını kullanın.";
                        if ($insStmt) {
                            $insStmt->bind_param('iisss', $devId, $portNo, $title, $message, $mac);
                            if ($insStmt->execute()) { $scan_created++; }
                        }
                    }
                    if ($insStmt)    { $insStmt->close(); }
                    if ($portIpStmt) { $portIpStmt->close(); }
                }
            }

            // ── Phase 3: Send email notification if new alarms were created ──
            if ($scan_created > 0) {
                $subject = "CHAMADA Kayıtsız MAC Alarm Özeti";
                $macContent = "<p style='margin:0 0 14px;font-size:15px;font-weight:700;color:#f59e0b;'>Kayıtsız MAC Alarm Özeti</p>"
                    . "<p style='margin:4px 0;'><strong style='color:#8899bb;'>Tarama sonucu:</strong> {$scan_total} kayıtsız MAC tespit edildi.</p>"
                    . "<p style='margin:4px 0;'><strong style='color:#8899bb;'>Oluşturulan alarmlar:</strong> <span style='color:#e74c3c;font-weight:700;'>{$scan_created}</span></p>"
                    . "<p style='margin:4px 0;'><strong style='color:#8899bb;'>Atlanan (mevcut aktif alarm):</strong> {$scan_skipped}</p>"
                    . "<p style='margin:16px 0 0;color:#8899bb;font-size:13px;'>Kayıtsız cihazları kayıt altına almak için <em>Device Import</em> sayfasını ziyaret edin.</p>";
                $htmlBody = chamada_email_template('Kayıtsız MAC Alarm Özeti', $macContent);
                $emailResult = sendAlarmEmail($subject, $htmlBody);
                $cfg = getSmtpConfig();
                if ($cfg) logEmailSent($subject, $cfg['to_addresses'] ?? [], 'alarm', $emailResult, 'unregistered_mac');
            }

            echo json_encode([
                'success'              => true,
                // apply_to_ports results
                'updated_count'        => $apply_updated_count,
                'updated_macs'         => array_values(array_unique($apply_updated_macs)),
                'already_current_macs' => array_values(array_unique($apply_already_current)),
                'matched_macs'         => array_values(array_unique(array_merge($apply_updated_macs, $apply_already_current))),
                'unmatched_macs'       => array_values(array_unique($apply_unmatched_macs)),
                // scan_unregistered results
                'total_unregistered'   => $scan_total,
                'alarms_created'       => $scan_created,
                'alarms_skipped'       => $scan_skipped,
                'ports_updated'        => $scan_ports_upd,
            ]);
        } catch (Exception $e) {
            echo json_encode(['success' => false, 'error' => $e->getMessage()]);
        }

        $conn->close();
        exit;
    }

    // Handle scan_unregistered action — find active MACs not in Device Import and alarm them
    if ($action === 'scan_unregistered') {
        $conn = getDBConnection();

        try {
            // Find MACs that appeared on a port in the last 24 hours
            // and are NOT present in mac_device_registry.
            // We use mac_address_tracking as the authoritative "currently active" source.
            // COLLATE utf8mb4_general_ci is applied to both sides to resolve the
            // collation mismatch between mac_address_tracking (utf8mb4_general_ci)
            // and mac_device_registry (utf8mb4_unicode_ci).
            $result = $conn->query("
                SELECT mat.mac_address,
                       mat.current_device_id,
                       mat.current_port_number,
                       mat.device_name,
                       mat.ip_address
                FROM mac_address_tracking mat
                LEFT JOIN mac_device_registry mdr
                       ON UPPER(REPLACE(mdr.mac_address, ':', '')) COLLATE utf8mb4_general_ci
                        = UPPER(REPLACE(mat.mac_address, ':', '')) COLLATE utf8mb4_general_ci
                LEFT JOIN port_status_data psd
                       ON psd.device_id   = mat.current_device_id
                      AND psd.port_number = mat.current_port_number
                WHERE mdr.mac_address IS NULL
                  AND mat.current_device_id IS NOT NULL
                  AND mat.last_seen >= DATE_SUB(NOW(), INTERVAL 24 HOUR)
                  AND (psd.vlan_id IS NULL OR psd.vlan_id NOT IN (70, 30, 40, 50, 130, 140, 254))
                ORDER BY mat.last_seen DESC
            ");

            if (!$result) {
                echo json_encode(['success' => false, 'error' => 'Veritabanı sorgusu başarısız: ' . $conn->error]);
                exit;
            }

            // Collect all candidate rows first, skipping locally-administered MACs.
            $candidates = [];
            while ($row = $result->fetch_assoc()) {
                $mac = strtoupper(trim($row['mac_address']));
                // Skip locally-administered (randomised/WiFi-client) MAC addresses.
                if (isLocallyAdministeredMac($mac)) {
                    continue;
                }
                $candidates[] = [
                    'mac'      => $mac,
                    'deviceId' => intval($row['current_device_id']),
                    'portNo'   => intval($row['current_port_number']),
                    'devName'  => $row['device_name'] ?? '',
                    'ip'       => $row['ip_address'] ?? '',
                ];
            }
            $result->close();

            $total_unregistered = count($candidates);
            $alarms_created     = 0;
            $alarms_skipped     = 0;
            $ports_updated      = 0;

            if ($total_unregistered > 0) {
                // Single query to find which of these MACs already have an ACTIVE mac_added alarm.
                $macList   = array_column($candidates, 'mac');
                $placeholders = implode(',', array_fill(0, count($macList), '?'));
                $types        = str_repeat('s', count($macList));
                $activeStmt   = $conn->prepare("
                    SELECT new_value FROM alarms
                    WHERE alarm_type = 'mac_added'
                      AND status = 'ACTIVE'
                      AND new_value IN ($placeholders)
                ");
                $activeStmt->bind_param($types, ...$macList);
                $activeStmt->execute();
                $activeRes = $activeStmt->get_result();
                $alreadyActive = [];
                while ($r = $activeRes->fetch_row()) {
                    $alreadyActive[$r[0]] = true;
                }
                $activeStmt->close();

                // Insert alarms only for MACs without an existing active alarm.
                // Also update ports.ip when mac_address_tracking has a valid IP for this MAC.
                $insStmt = $conn->prepare("
                    INSERT INTO alarms
                        (device_id, port_number, alarm_type, severity, status,
                         title, message, old_value, new_value,
                         first_occurrence, last_occurrence, occurrence_count,
                         created_at, updated_at)
                    VALUES (?, ?, 'mac_added', 'MEDIUM', 'ACTIVE',
                            ?, ?, '', ?,
                            NOW(), NOW(), 1, NOW(), NOW())
                ");

                $portIpStmt = $conn->prepare("
                    UPDATE ports
                    SET ip = ?
                    WHERE LOWER(REPLACE(mac, ':', '')) = ?
                      AND mac IS NOT NULL
                      AND mac != ''
                      AND (ip IS NULL OR ip = '')
                ");

                foreach ($candidates as $c) {
                    $mac     = $c['mac'];
                    $devId   = $c['deviceId'];
                    $portNo  = $c['portNo'];
                    $devName = $c['devName'];
                    $ip      = $c['ip'];

                    // Write IP to ports table if mac_address_tracking has a valid one
                    // and the port doesn't already have an IP set.
                    if (!empty($ip) && validateIP($ip) && $portIpStmt) {
                        $macNorm = strtolower(str_replace(':', '', $mac));
                        $portIpStmt->bind_param('ss', $ip, $macNorm);
                        executeWithDeadlockRetry($portIpStmt);
                        if ($portIpStmt->affected_rows > 0) {
                            $ports_updated++;
                        }
                    }

                    if (isset($alreadyActive[$mac])) {
                        $alarms_skipped++;
                        continue;
                    }

                    $title   = "Kayıtsız MAC: $mac";
                    $message = "Port $portNo üzerinde Device Import kaydı olmayan MAC tespit edildi: $mac" .
                               ($ip ? " (IP: $ip)" : '') .
                               ($devName ? " (Cihaz: $devName)" : '') .
                               ". Cihazı kaydetmek için Device Import sayfasını kullanın.";

                    $insStmt->bind_param('iisss', $devId, $portNo, $title, $message, $mac);
                    if ($insStmt->execute()) {
                        $alarms_created++;
                    }
                }
                $insStmt->close();
                if ($portIpStmt) {
                    $portIpStmt->close();
                }
            }

            // Send email notification if new alarms were created
            if ($alarms_created > 0) {
                $subject = "CHAMADA Kayıtsız MAC Alarm Özeti";
                $macContent2 = "<p style='margin:0 0 14px;font-size:15px;font-weight:700;color:#f59e0b;'>Kayıtsız MAC Alarm Özeti</p>"
                    . "<p style='margin:4px 0;'><strong style='color:#8899bb;'>Tarama sonucu:</strong> {$total_unregistered} kayıtsız MAC tespit edildi.</p>"
                    . "<p style='margin:4px 0;'><strong style='color:#8899bb;'>Oluşturulan alarmlar:</strong> <span style='color:#e74c3c;font-weight:700;'>{$alarms_created}</span></p>"
                    . "<p style='margin:4px 0;'><strong style='color:#8899bb;'>Atlanan (mevcut aktif alarm):</strong> {$alarms_skipped}</p>"
                    . "<p style='margin:16px 0 0;color:#8899bb;font-size:13px;'>Kayıtsız cihazları kayıt altına almak için <em>Device Import</em> sayfasını ziyaret edin.</p>";
                $htmlBody = chamada_email_template('Kayıtsız MAC Alarm Özeti', $macContent2);
                $emailResult2 = sendAlarmEmail($subject, $htmlBody);
                $cfg2 = getSmtpConfig();
                if ($cfg2) logEmailSent($subject, $cfg2['to_addresses'] ?? [], 'alarm', $emailResult2, 'unregistered_mac');
            }

            echo json_encode([
                'success'            => true,
                'total_unregistered' => $total_unregistered,
                'alarms_created'     => $alarms_created,
                'alarms_skipped'     => $alarms_skipped,
                'ports_updated'      => $ports_updated,
            ]);
        } catch (Exception $e) {
            echo json_encode(['success' => false, 'error' => $e->getMessage()]);
        }

        $conn->close();
        exit;
    }

    // Handle apply_to_ports action
    if ($action === 'apply_to_ports') {
        $conn = getDBConnection();
        
        try {
            // Get all devices from registry.
            // Exclude snmp_hub_auto entries: those have VLAN labels (e.g. "50", "JACKPOT")
            // as placeholders, not real IP addresses or hostnames. Writing them to the
            // ports table would corrupt the port display with VLAN-name strings.
            // Only excel/manual entries (real user-supplied data) should be applied.
            // ip_address is NOT required: devices imported with MAC + device_name only
            // are still applied (existing port IP is preserved via COALESCE in the UPDATE).
            $result = $conn->query("
                SELECT mac_address, ip_address, device_name 
                FROM mac_device_registry 
                WHERE mac_address IS NOT NULL 
                AND device_name IS NOT NULL
                AND (source IS NULL OR source != 'snmp_hub_auto')
            ");
            
            if (!$result) {
                echo json_encode(['success' => false, 'error' => 'Database query failed']);
                exit;
            }
            
            $updated_count = 0;
            $updated_macs = [];
            $already_current_macs = [];
            $unmatched_macs = [];

            // Load MACs that were previously matched (ever seen by SNMP) so
            // that temporarily-offline devices are not re-labelled as unmatched.
            // Only MACs that have NEVER been seen by SNMP should get 'unmatched'.
            $prevMatchedSet = [];
            $prevColCheck2 = $conn->query("SHOW COLUMNS FROM mac_device_registry LIKE 'match_status'");
            if ($prevColCheck2 && $prevColCheck2->num_rows > 0) {
                $prevRes2 = $conn->query("SELECT mac_address FROM mac_device_registry WHERE match_status IN ('updated', 'already_current')");
                if ($prevRes2) {
                    while ($r2 = $prevRes2->fetch_assoc()) {
                        $prevMatchedSet[strtolower(str_replace(':', '', $r2['mac_address']))] = true;
                    }
                    $prevRes2->close();
                }
            }
            
            // For each device, find and update matching ports
            while ($device = $result->fetch_assoc()) {
                $mac = $device['mac_address'];
                $ip = $device['ip_address'] ?? '';
                $hostname = $device['device_name'];

                // Skip entries where ip_address is present but not a valid IP address.
                // VLAN labels (e.g. "50", "JACKPOT") may appear as placeholders
                // in registry entries whose source was previously 'snmp_hub_auto'
                // or that were imported with non-IP values.  Writing such strings
                // to ports.ip corrupts the hub-port display in the UI.
                // Empty/NULL ip_address is allowed: only the device name is written and
                // the existing port IP is preserved via COALESCE in the UPDATE statement.
                if (!empty($ip) && !validateIP($ip)) {
                    continue;
                }

                // Normalize MAC for comparison (remove colons, lowercase)
                $macNormalized = strtolower(str_replace(':', '', $mac));

                // ── Primary check: MAC present in ports.mac ──────────────────
                // Hub-switch ports store multiple MACs comma-separated
                // (e.g. "aa:bb:cc:11:11:11,dd:ee:ff:22:22:22"), so we use
                // FIND_IN_SET against the colon-stripped, lower-cased value
                // instead of an exact equality check.
                $checkStmt = $conn->prepare("
                    SELECT COUNT(*) as cnt FROM ports WITH(NOLOCK)
                    WHERE CHARINDEX(?, LOWER(REPLACE(mac, ':', ''))) > 0
                    AND mac IS NOT NULL
                    AND mac != ''
                ");
                $portExists = false;
                if ($checkStmt) {
                    $checkStmt->bind_param('s', $macNormalized);
                    $checkStmt->execute();
                    $checkResult = $checkStmt->get_result();
                    $portExists = ($checkResult->fetch_assoc()['cnt'] ?? 0) > 0;
                    $checkStmt->close();
                }

                // ── Fallback: MAC tracked by SNMP but aged out of FDB ────────
                // Devices behind hub/unmanaged switches are tracked in
                // mac_address_tracking individually.  When a MAC ages out of
                // the switch FDB (typically after 300 s of inactivity), the
                // SNMP worker replaces ports.mac with only the still-visible
                // MACs, causing the FIND_IN_SET above to fail even though the
                // device IS physically connected and was recently seen.
                // We fall back to mac_address_tracking to detect these cases.
                $trackingPortId = null;
                if (!$portExists) {
                    $macHex = strtoupper(str_replace(':', '', $mac));
                    $tStmt = $conn->prepare("
                        SELECT p.id
                        FROM mac_address_tracking mat
                        JOIN snmp_devices sd ON sd.id = mat.current_device_id
                        JOIN switches sw ON sw.name = sd.name
                        JOIN ports p ON p.switch_id = sw.id
                                     AND p.port_no = mat.current_port_number
                        WHERE UPPER(REPLACE(mat.mac_address, ':', '')) = ?
                        LIMIT 1
                    ");
                    if ($tStmt) {
                        $tStmt->bind_param('s', $macHex);
                        $tStmt->execute();
                        $tResult = $tStmt->get_result();
                        if ($tRow = $tResult->fetch_assoc()) {
                            $portExists    = true;
                            $trackingPortId = (int)$tRow['id'];
                        }
                        $tStmt->close();
                    }
                }

                if (!$portExists) {
                    // If this MAC was seen by SNMP in a previous run, it is
                    // temporarily offline — preserve its matched status rather
                    // than marking it unmatched. Only devices that have NEVER
                    // been matched should receive the 'unmatched' label.
                    if (isset($prevMatchedSet[$macNormalized])) {
                        $already_current_macs[] = $mac;
                    } else {
                        $unmatched_macs[] = $mac;
                    }
                }

                // ── Update ports table ────────────────────────────────────────
                if ($trackingPortId !== null) {
                    // MAC found via mac_address_tracking (not currently in
                    // ports.mac).  Update the port's device label and IP by ID,
                    // and append the MAC to ports.mac so future FIND_IN_SET
                    // checks work without requiring another tracking lookup.
                    // COALESCE(NULLIF(ip, ''), existing_ip) preserves the current
                    // port IP when no IP was supplied in the registry entry.
                    $updStmt = $conn->prepare("
                        UPDATE ports
                        SET ip     = COALESCE(NULLIF(?, ''), ip),
                            device = ?,
                            mac    = CASE
                                         WHEN (mac IS NULL OR mac = '') THEN ?
                                         ELSE CONCAT(mac, ',', ?)
                                     END
                        WHERE id = ?
                          AND CHARINDEX(?, LOWER(REPLACE(COALESCE(mac,''), ':', ''))) = 0
                    ");
                    if ($updStmt) {
                        $macColon = $mac; // original colon-separated format
                        $updStmt->bind_param('ssssis', $ip, $hostname, $macColon, $macColon, $trackingPortId, $macNormalized);
                        executeWithDeadlockRetry($updStmt);
                        $rowsAffected = $updStmt->affected_rows;
                        if ($rowsAffected > 0) {
                            $updated_macs[]  = $mac;
                            $updated_count  += $rowsAffected;
                        } else {
                            $already_current_macs[] = $mac;
                        }
                        $updStmt->close();
                    } else {
                        $already_current_macs[] = $mac;
                    }
                } else {
                    // Update ports table (same as Port Edit uses).
                    // Use FIND_IN_SET for the WHERE clause so that hub-switch
                    // ports (which store all connected device MACs
                    // comma-separated) are matched correctly alongside
                    // single-MAC ports.
                    // NOTE: connection_info is intentionally NOT updated here —
                    // it stores panel connection JSON (written by saveportwithpanel.php /
                    // paneltoswitchconnection.php) and must not be overwritten with a
                    // plain hostname string from the MAC registry.
                    // COALESCE(NULLIF(ip, ''), existing_ip) preserves the current
                    // port IP when no IP was supplied in the registry entry.
                    $updateStmt = $conn->prepare("
                        UPDATE ports WITH (ROWLOCK)
                        SET ip = COALESCE(NULLIF(?, ''), ip), 
                            device = ?
                        WHERE CHARINDEX(?, LOWER(REPLACE(mac, ':', ''))) > 0
                        AND mac IS NOT NULL 
                        AND mac != ''
                    ");
                    if ($updateStmt) {
                        $updateStmt->bind_param('sss', $ip, $hostname, $macNormalized);
                        executeWithDeadlockRetry($updateStmt);
                        $rowsAffected = $updateStmt->affected_rows;
                        if ($portExists) {
                            if ($rowsAffected > 0) {
                                $updated_macs[]  = $mac;
                                $updated_count  += $rowsAffected;
                            } else {
                                $already_current_macs[] = $mac;
                            }
                        }
                        $updateStmt->close();
                    }
                }
            }
            
            $result->close();

            // Persist match_status in the DB so the filter buttons can query it
            // without sending large MAC lists over the wire.
            // The match_status column is added by migration 68 in update_database.php.
            // If it exists, update it; if not, skip silently (filter will show all).
            $colCheck = $conn->query("SHOW COLUMNS FROM mac_device_registry LIKE 'match_status'");
            if ($colCheck && $colCheck->num_rows > 0) {
                // Reset only previously-set rows to avoid unnecessary writes
                $conn->query("UPDATE mac_device_registry SET match_status = NULL WHERE match_status IS NOT NULL");
                // Batch-update each category
                $allUpdated   = array_values(array_unique($updated_macs));
                $allCurrent   = array_values(array_unique($already_current_macs));
                $allUnmatched = array_values(array_unique($unmatched_macs));
                $statusBatch  = [
                    'updated'         => $allUpdated,
                    'already_current' => $allCurrent,
                    'unmatched'       => $allUnmatched,
                ];
                foreach ($statusBatch as $statusVal => $macList) {
                    foreach ($macList as $m) {
                        $stStmt = $conn->prepare("UPDATE mac_device_registry SET match_status = ? WHERE mac_address = ?");
                        if ($stStmt) {
                            $stStmt->bind_param('ss', $statusVal, $m);
                            $stStmt->execute();
                            $stStmt->close();
                        }
                    }
                }
            }

            echo json_encode([
                'success' => true,
                'updated_count' => $updated_count,
                'message' => "$updated_count port description(s) updated with Device Import data",
                'updated_macs' => array_values(array_unique($updated_macs)),
                'already_current_macs' => array_values(array_unique($already_current_macs)),
                'matched_macs' => array_values(array_unique(array_merge($updated_macs, $already_current_macs))),
                'unmatched_macs' => array_values(array_unique($unmatched_macs))
            ]);
        } catch (Exception $e) {
            echo json_encode(['success' => false, 'error' => $e->getMessage()]);
        }
        
        $conn->close();
        exit;
    }
}

// Handle DELETE
if ($_SERVER['REQUEST_METHOD'] === 'DELETE' || ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_GET['_method']) && $_GET['_method'] === 'DELETE')) {
    // Use the raw value stored in mac_address (may be a port name, not a
    // standard MAC) – normalizeMac() would return null for those identifiers.
    $mac = isset($_GET['mac']) ? trim($_GET['mac']) : null;
    
    if (!$mac) {
        echo json_encode(['error' => 'MAC address required']);
        exit;
    }
    
    $conn = getDBConnection();
    $stmt = $conn->prepare("DELETE FROM mac_device_registry WHERE mac_address = ?");
    $stmt->bind_param('s', $mac);
    
    if ($stmt->execute()) {
        echo json_encode(['success' => true, 'message' => 'Device deleted']);
    } else {
        echo json_encode(['error' => 'Failed to delete device']);
    }
    
    $stmt->close();
    $conn->close();
    exit;
}

echo json_encode(['error' => 'Invalid request method']);
?>
